export const routeMap: Record<string, Record<string, string>> = {
  sr: {
    home: "/",
    about: "/o-osnivacu",
    services: "/terapijske-usluge",
    faq: "/najcesca-pitanja",
    gallery: "/galerija",
    reviews: "/utisci",
    contact: "/kontakt",
    endodontics: "/terapijske-usluge/endodoncija",
    conservative: "/terapijske-usluge/konzervativna-stomatologija",
    whitening: "/terapijske-usluge/izbeljivanje",
    orthodontics: "/terapijske-usluge/ortodoncija",
    examination: "/terapijske-usluge/pregled",
    prosthetics: "/terapijske-usluge/protetska-hirurgija",
    TMJ: "/terapijske-usluge/terapija-donjovilicnog-zgloba",
  },
  en: {
    home: "/en",
    about: "/en/about",
    services: "/en/services",
    faq: "/en/faqs",
    gallery: "/en/photo-gallery",
    reviews: "/en/reviews",
    contact: "/en/contact",
    endodontics: "/en/services/endodontics",
    conservative: "/en/services/conservative-dentistry",
    whitening: "/en/services/whitening",
    orthodontics: "/en/services/orthodontics",
    examination: "/en/services/examination",
    prosthetics: "/en/services/prosthetic-surgery",
    TMJ: "/en/services/temporomandibular-joint-therapy",
  },
};
