export const routeMap: Record<string, Record<string, string>> = {
  sr: {
    home: "/",
    about: "/o-osnivacu",
    services: "/terapijske-usluge",
    faq: "/najcesca-pitanja",
    gallery: "/galerija",
    testimonials: "/utisci",
    contact: "/kontakt",
    endodontics: "/terapijske-usluge/endodoncija",
    conservative: "/terapijske-usluge/konzervativna-stomatologija",
    whitening: "/terapijske-usluge/izbeljivanje",
    orthodontics: "/terapijske-usluge/terapija-folijama",
    examination: "/terapijske-usluge/pregled",
    prosthetics: "/terapijske-usluge/protetska-hirurgija",
  },
  en: {
    home: "/en",
    about: "/en/about",
    services: "/en/services",
    faq: "/en/faqs",
    gallery: "/en/photo-gallery",
    testimonials: "/en/testimonials",
    contact: "/en/contact",
    endodontics: "/en/services/endodontics",
    conservative: "/en/services/conservative-dentistry",
    whitening: "/en/services/whitening",
    orthodontics: "/en/services/foil-therapy",
    examination: "/en/services/examination",
    prosthetics: "/en/services/prosthetic-surgery",
  },
};
